apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-envoy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-envoy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-envoy
    spec:
      containers:
      - name: {{ .Release.Name }}-envoy
        image: envoyproxy/envoy-alpine:v1.9.1
        ports:
        - name: https
          containerPort: 443
        imagePullPolicy: Always
        volumeMounts:
          - name: config-volume
            mountPath: /etc/envoy/
          # - name: jwks-volume
          #   mountPath: /etc/envoy/jwks
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-maintemplate-envoy-config
        # - name: jwks-volume
        #   persistentVolumeClaim:
        #     claimName: {{ .Release.Name }}-paas-envoy-local-jwks-claims
