name: gcloud

on:
  pull_request:
    branches:
      - "*"

jobs:
  all:
    name: gcloud
   
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go-version: [1.15.2]
        target: ["this-all",]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Info
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: v2-ci-getcouragenow-org
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY }}
        with:
          args: info

    